comment: false
codecov:
  branch: master

coverage:
  precision: 2
  status:
    patch: false
    project:
      default:
        target: 100%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

ignore:
  - "^tests.*"